version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    assignees:
      - 'IsmaellHV'
    reviewers:
      - 'IsmaellHV'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
